import React, { useState } from "react";
import HeaderTwo from "../../../components/HeaderTwo";
import HeaderThree from "../../../components/HeaderThree";
import SectionTwo from "../../../components/SectionTwo";
import WorkExperienceCard from "../../../components/WorkExperienceCard";
import WorkExperienceDescription from "../../../components/WorkExperienceDesciption";
import WorkExperienceModal from "../../../components/WorkExperienceModal";

function WorkExperience() {
  const [hoveredWorkExperience, setHoveredWorkExperience] = useState("");
  const [clickedWorkExperience, setClickedWorkExperience] = useState("");

  const workExperienceList = [
    { colour: "#9F3B47", rotate: "5deg", top: { default: "40px", sm: "60px", md: "80px", lg: "100px" },  information: { title: "Product Manager", company: "Mastercard", description: ["Worked in the product team that leads Click-to-pay in Australia", "Uplifted Click-to-pay within Australia, with total transactions growing 17%", "Developed Click-to-pay's integration within Menulog and secured contractual agreement", "Designed and	optimised UX flows for Click-to-pay experience with Australia's largest merchants, including Chemist Warehouse and Ticketek"]}},
    { colour: "#D37B44", rotate: "-5deg", top: { default: "80px", sm: "120px", md: "160px", lg: "200px" }, information: { title: "Human Centred Design", company: "ASIC",  description: ["Worked on projects for ASIC to uplift products and create new products that impacts 100,000+ organisations", "Conducted user research and usability testing with regulated organisations", "Lead the Moneysmart Homepage usability research project", "Assisted with navigating ambiguous problem spaces and ideating solutions", "Contributed to ASIC's 2030 digital vision to \"become a leading digitally enabled and data-informed regulator by 2030\""]}},
    { colour: "#B25754", rotate: "10deg", top: { default: "120px", sm: "180px", md: "240px", lg: "300px" }, information: { title: "Technical Business Analyst", company: "ASIC",  description: ["Drove innovation within Digital Applications team at ASIC", "Developed templates to automate PDF generation for Professional Search Register", "Tested and analysed the release of new products, including Australian Financial Service Licence application form"]}},
    { colour: "#9F3B47", rotate: "-9deg", top: { default: "160px", sm: "240px", md: "320px", lg: "400px" }, information: { title: "Digital Journey Optimisation", company: "CBA",  description: ["Drove innovation and customer experience with CommBank's new loyalty program ~ Yello", "Created and tested assets that was deliver to the live CommBank application to millions of customers", "Streamlined internal processes to reduce time by 50% for asset generation for Yello", "Conducted in-depth competitor research"]}},
    { colour: "#D37B44", rotate: "10deg", top: { default: "200px", sm: "300px", md: "400px", lg: "500px" }, information: { title: "Digital A.I. Engineer", company: "Optus",  description: ["Drove innovation in an agile environment through the creation of analytical business intelligent assets and dashboards to help efficiency and effectiveness of data-driven business decision", "Developed an application to automate dashboard creation processes, reducing processes from a week to a few hours", "Managed multiple stakeholders and prioritised value creation generated by actionable-level and analytical insights"]}},
  ];

  return (
    <SectionTwo>
      <div className="flex flex-col md:flex-row gap-[50px] md:gap-[100px] justify-between h-auto">
        <div className="flex flex-col gap-11">
          <HeaderTwo className="text-center md:text-left">Work Experience.</HeaderTwo>
          <HeaderThree className="text-center md:text-left">In the past I have worked at various different organisations (as an intern).</HeaderThree>
          {clickedWorkExperience || hoveredWorkExperience
            ? <div 
                className="hidden md:block h-auto w-full rounded-xl flex items-center justify-center sticky top-[3vh] lg:top-[10vh] xl:top-[20vh] self-start"
                style={{ borderColor: clickedWorkExperience?.colour || hoveredWorkExperience?.colour, borderWidth: "5px" }}
              >
                <WorkExperienceDescription workExperience={clickedWorkExperience.information || hoveredWorkExperience.information} />
              </div>
            : <div className="hidden border border-white border-[5px] md:block h-[50vh] w-full rounded-xl flex items-center justify-center sticky top-[3vh] lg:top-[10vh] xl:top-[20vh] self-start" />
          }
        </div>
        <div className="w-full md:w-auto flex justify-center md:justify-start">
          <div className="flex flex-col gap-[30vh] w-[80%] md:w-auto">
            {workExperienceList.map((workExperience, index) => (
              <WorkExperienceCard
                workExperience={workExperience.information}
                colour={workExperience.colour}
                rotate={workExperience.rotate}
                top={workExperience.top}
                key={`workExperience-${index}`}
                onMouseEnter={() => setHoveredWorkExperience(workExperience)}
                onMouseLeave={() => setHoveredWorkExperience("")}
                onClick={() => setClickedWorkExperience(
                  clickedWorkExperience?.information?.title === workExperience.information.title
                    ? "" : workExperience
                )}
                selected={clickedWorkExperience?.information?.title === workExperience.information.title}
              />
            ))}
          </div>
        </div>
      </div>
      <WorkExperienceModal
        workExperience={clickedWorkExperience}
        isOpen={!!clickedWorkExperience}
        onClose={() => setClickedWorkExperience("")}
      />
    </SectionTwo>
  );
}

export default WorkExperience;
